import type { CatalogRouteGroup, CatalogSectionSlug } from "@/types";

export const routeGroups: CatalogRouteGroup[] = [
  // ── American Standard ──────────────────────────────────────────────────────
  {
    section: "door-hardware",
    familySlug: "american-standard",
    familyTitle: "American Standard",
    slug: "hang-the-door",
    title: "Hang The Door",
    description:
      "Coordinated hanging hardware for architectural door sets — hinges, pivots, concealed hinges and related leaf-support components.",
    shortDescription:
      "Hinges, pivots and concealed hanging hardware for architectural door sets.",
    image: "/tur/door-hardware/categories/default-1260902568201015.jpg",
    imageAlt: "American Standard hanging hardware — hinges and door preparation components",
    eyebrow: "American Standard · Hanging Hardware",
    keywords: [
      "spring hinges",
      "full mortise hinges",
      "continuous hinges",
      "concealed bearing hinges",
      "ANSI door hinges",
      "door hanging hardware",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "american-standard",
    familyTitle: "American Standard",
    slug: "control-the-door",
    title: "Control The Door",
    description:
      "Door closers, floor springs and controlled movement hardware for dependable closing performance across commercial and institutional applications.",
    shortDescription:
      "Overhead closers and floor springs for controlled door movement.",
    image: "/tur/door-hardware/categories/default-319952360201015.jpg",
    imageAlt: "American Standard door closer — overhead control hardware",
    eyebrow: "American Standard · Control Hardware",
    keywords: [
      "door closers",
      "floor springs",
      "overhead closers",
      "ANSI door closers",
      "concealed door closer",
      "door control hardware",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "american-standard",
    familyTitle: "American Standard",
    slug: "secure-the-door",
    title: "Secure The Door",
    description:
      "Mortise locks, cylindrical locks, deadbolts and hook locks for secure openings across American Standard hardware schedules.",
    shortDescription:
      "Mortise locks, deadbolts and locking hardware for secure openings.",
    image: "/tur/door-hardware/categories/default-1292769047201015.jpg",
    imageAlt: "American Standard mortise lockset and cylinder — door security hardware",
    eyebrow: "American Standard · Security Hardware",
    legacyEntryCount: 13,
    keywords: [
      "mortise locks",
      "deadbolts",
      "cylindrical locks",
      "ANSI locks",
      "door security hardware",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "american-standard",
    familyTitle: "American Standard",
    slug: "furnish-the-door",
    title: "Furnish The Door",
    description:
      "Lever handles, rose plates, escutcheons and trim that complete the architectural door-set package under American Standard specifications.",
    shortDescription:
      "Lever handles, trim and finishing hardware for American Standard door sets.",
    image: "/tur/door-hardware/categories/default-1228180766201015.jpg",
    imageAlt: "American Standard lever handle and trim hardware",
    eyebrow: "American Standard · Furnishing Hardware",
    keywords: [
      "lever handles",
      "ANSI lever handles",
      "door trim",
      "escutcheons",
      "door furnishing",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "american-standard",
    familyTitle: "American Standard",
    slug: "bolt-the-door",
    title: "Bolt The Door",
    description:
      "Flush bolts, surface bolts and coordinated bolting hardware for paired and single door sets in American Standard specifications.",
    shortDescription:
      "Flush and surface bolts for coordinated American Standard door sets.",
    image: "/tur/door-hardware/categories/default-517696467201015.jpg",
    imageAlt: "American Standard flush bolt — door bolting hardware",
    eyebrow: "American Standard · Bolting Hardware",
    keywords: [
      "flush bolts",
      "surface bolts",
      "door bolts",
      "ANSI bolts",
      "door bolting hardware",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "american-standard",
    familyTitle: "American Standard",
    slug: "emergency-exits",
    title: "Emergency Exits",
    description:
      "Panic hardware, rim exit devices, vertical-rod devices and life-safety components for compliant emergency egress conditions.",
    shortDescription:
      "Panic hardware and exit devices for compliant emergency egress.",
    image: "/tur/door-hardware/categories/default-848766351201015.jpg",
    imageAlt: "Emergency exit hardware — panic bar and life-safety door devices",
    eyebrow: "American Standard · Life Safety",
    keywords: [
      "panic hardware",
      "exit devices",
      "rim exit device",
      "vertical rod device",
      "emergency exit hardware",
      "life safety hardware",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "american-standard",
    familyTitle: "American Standard",
    slug: "ancillary-products",
    title: "Ancillary Products",
    description:
      "Supporting hardware, protective plates, viewers, knockers and complementary accessories that complete coordinated American Standard door packages.",
    shortDescription:
      "Accessories and supporting hardware to complete American Standard packages.",
    image: "/tur/door-hardware/categories/default-355604123201015.jpg",
    imageAlt: "American Standard ancillary hardware components",
    eyebrow: "American Standard · Ancillary",
    keywords: [
      "door accessories",
      "protective plates",
      "door viewers",
      "door knockers",
      "ancillary hardware",
    ],
  },

  // ── European Ironmongery ──────────────────────────────────────────────────
  {
    section: "door-hardware",
    familySlug: "european-ironmongery",
    familyTitle: "European Ironmongery",
    slug: "hang-the-door",
    title: "Hang The Door",
    description:
      "European Ironmongery hanging hardware from the old TUR catalogue, including TE4100 full mortise hinges, rising hinges, concealed hinges and heavy duty double action spring hinges.",
    shortDescription:
      "Hinges and hanging hardware for European Ironmongery door sets.",
    image: "/tur/door-hardware/european-ironmongery/hang-the-door/te4100-series/te4100-series-main.jpg",
    imageAlt: "TE4100 Series full mortise hinge — European Ironmongery hanging hardware",
    eyebrow: "European Ironmongery · Hanging Hardware",
    keywords: ["TE4100", "rising hinges", "concealed hinges", "European door hinges"],
  },
  {
    section: "door-hardware",
    familySlug: "european-ironmongery",
    familyTitle: "European Ironmongery",
    slug: "control-the-door",
    title: "Control The Door",
    description:
      "Door closers, concealed closers, cam-action closers, hydraulic patch fittings and floor springs from the European Ironmongery old-site catalogue.",
    shortDescription:
      "Closers, patch fittings and floor springs for European Ironmongery door control.",
    image: "/tur/door-hardware/european-ironmongery/control-the-door/door-closer-rack-pinion-track-arm-te7763b/door-closer-rack-pinion-track-arm-te7763b-main.jpg",
    imageAlt: "TE7763B rack and pinion door closer with track arm — European Ironmongery control hardware",
    eyebrow: "European Ironmongery · Control Hardware",
    keywords: ["door closer", "TE7763B", "floor spring", "hydraulic patch fitting"],
  },
  {
    section: "door-hardware",
    familySlug: "european-ironmongery",
    familyTitle: "European Ironmongery",
    slug: "secure-the-door",
    title: "Secure The Door",
    description:
      "TE1400 and TE1500 mortise lock bodies, latch locks, deadbolt locks, hook locks and narrow stile locks from the European Ironmongery catalogue.",
    shortDescription:
      "Mortise locks, deadbolts, hook locks and narrow stile locks.",
    image: "/tur/door-hardware/european-ironmongery/secure-the-door/te1400-series-mortise-sash-lock-premium/te1400-series-mortise-sash-lock-premium-main.jpg",
    imageAlt: "TE1400 Series mortise sash lock — European Ironmongery security hardware",
    eyebrow: "European Ironmongery · Security Hardware",
    keywords: ["TE1400", "TE1500", "mortise sash lock", "hook lock"],
  },
  {
    section: "door-hardware",
    familySlug: "european-ironmongery",
    familyTitle: "European Ironmongery",
    slug: "cylinders",
    title: "Cylinders",
    description:
      "European profile cylinder products from the old TUR catalogue, including TE3600 and TE3700 series cylinder pages.",
    shortDescription: "European profile cylinder series for keyed access coordination.",
    image: "/tur/door-hardware/european-ironmongery/cylinders/te3600-series/te3600-series-main.jpg",
    imageAlt: "TE3600 Euro profile cylinder — European Ironmongery keyed hardware",
    eyebrow: "European Ironmongery · Cylinders",
    keywords: ["TE3600", "TE3700", "Euro profile cylinders", "door cylinders"],
  },
  {
    section: "door-hardware",
    familySlug: "european-ironmongery",
    familyTitle: "European Ironmongery",
    slug: "furnish-the-door",
    title: "Furnish The Door",
    description:
      "Pull plates, pull handles and special handles from the European Ironmongery furnishing route.",
    shortDescription: "Pull plates and pull-handle families for European Ironmongery.",
    image: "/tur/door-hardware/european-ironmongery/furnish-the-door/pull-plates-european/pull-plates-european-main.jpg",
    imageAlt: "European Ironmongery pull plates — furnishing hardware",
    eyebrow: "European Ironmongery · Furnishing Hardware",
    keywords: ["pull plates", "H shape pull handle", "D shape pull handle", "special handles"],
  },
  {
    section: "door-hardware",
    familySlug: "european-ironmongery",
    familyTitle: "European Ironmongery",
    slug: "bolt-the-door",
    title: "Bolt The Door",
    description:
      "Lever action flush bolts, automatic flush bolts and dust proof strikes from the European Ironmongery bolting route.",
    shortDescription: "Flush bolts and strike hardware for European Ironmongery door sets.",
    image: "/tur/door-hardware/european-ironmongery/bolt-the-door/lever-action-flush-bolt-european/lever-action-flush-bolt-european-main.jpg",
    imageAlt: "European Ironmongery lever action flush bolt — bolting hardware",
    eyebrow: "European Ironmongery · Bolting Hardware",
    keywords: ["lever action flush bolt", "automatic flush bolt", "dust proof strike"],
  },
  {
    section: "door-hardware",
    familySlug: "european-ironmongery",
    familyTitle: "European Ironmongery",
    slug: "ancillary-products",
    title: "Ancillary Products",
    description:
      "Door stops, indicators, guards, viewers, escutcheons, pulls, plates, sockets, roller latches, coat hooks and sign plates from the European Ironmongery accessory route.",
    shortDescription: "Accessory and completion hardware for European Ironmongery packages.",
    image: "/tur/door-hardware/european-ironmongery/ancillary-products/door-stop-european/door-stop-european-main.jpg",
    imageAlt: "European Ironmongery door stop — ancillary hardware",
    eyebrow: "European Ironmongery · Ancillary",
    keywords: ["door stop", "thumb turn indicator", "door viewer", "sign plates"],
  },
  {
    section: "door-hardware",
    familySlug: "european-ironmongery",
    familyTitle: "European Ironmongery",
    slug: "emergency-exits",
    title: "Emergency Exits",
    description:
      "TE9800 and TE9700 exit device series, vertical rod devices, rim devices and escutcheon trims from the European Ironmongery emergency exit route.",
    shortDescription: "Exit devices and trim hardware for European Ironmongery egress.",
    image: "/tur/door-hardware/european-ironmongery/emergency-exits/te9800-series-premium/te9800-series-premium-main.jpg",
    imageAlt: "TE9800 Series premium exit device — European Ironmongery life safety hardware",
    eyebrow: "European Ironmongery · Life Safety",
    keywords: ["TE9800", "TE9700", "exit device", "escutcheon trim"],
  },
  {
    section: "door-hardware",
    familySlug: "european-ironmongery",
    familyTitle: "European Ironmongery",
    slug: "furnish-the-door-lever-handle",
    title: "Furnish The Door Lever Handle",
    description:
      "TE1910 and TE1920 lever and knob handle pages from the old TUR European Ironmongery lever-handle route.",
    shortDescription: "TE1910 and TE1920 lever and knob handle designs.",
    image: "/tur/door-hardware/european-ironmongery/furnish-the-door-lever-handle/lever-handle-te1910-968/lever-handle-te1910-968-main.jpg",
    imageAlt: "TE1910.968 lever handle — European Ironmongery lever and knob handles",
    eyebrow: "European Ironmongery · Lever Handles",
    keywords: ["TE1910", "TE1920", "lever handle", "knob handle"],
  },

  // Glass Hardware
  {
    section: "door-hardware",
    familySlug: "glass-hardware",
    familyTitle: "Glass Hardware",
    slug: "glass-hinge-glass-clip",
    title: "Glass Hinge & Glass Clip",
    description:
      "TG.GH glass hinge and glass clip products from the old TUR Glass Hardware catalogue.",
    shortDescription: "TG.GH glass hinge and clip products for frameless glass applications.",
    image: "/tur/door-hardware/categories/default-2080527890201111.jpg",
    imageAlt: "TG.GH glass hinge and glass clip — frameless door hardware",
    eyebrow: "Glass Hardware - Hinge & Clip",
    keywords: ["TG.GH101", "glass hinge", "glass clip", "Glass Hardware"],
  },
  {
    section: "door-hardware",
    familySlug: "glass-hardware",
    familyTitle: "Glass Hardware",
    slug: "bathroom-handle-glass-knob",
    title: "Bathroom Handle & Glass Knob",
    description:
      "Bathroom handle and glass knob products from the old TUR Glass Hardware catalogue.",
    shortDescription: "TG.BH and TG.GK bathroom handle and glass knob products.",
    image: "/tur/door-hardware/categories/default-1966218428201111.jpg",
    imageAlt: "TG.BH bathroom handle and TG.GK glass knob — glass hardware",
    eyebrow: "Glass Hardware - Handles & Knobs",
    keywords: ["TG.BH101", "TG.GK102", "bathroom handle", "glass knob"],
  },
  {
    section: "door-hardware",
    familySlug: "glass-hardware",
    familyTitle: "Glass Hardware",
    slug: "patch-fitting",
    title: "Patch Fitting",
    description:
      "TG.PF and TG.FS patch fitting products from the old TUR Glass Hardware catalogue.",
    shortDescription: "TG.PF patch fitting products for glass hardware schedules.",
    image: "/tur/door-hardware/categories/default-45651367201111.jpg",
    imageAlt: "TG.PF patch fitting — frameless glass door hardware",
    eyebrow: "Glass Hardware - Patch Fittings",
    keywords: ["TG.PF101", "TG.PF103", "patch fitting", "Glass Hardware"],
  },
  {
    section: "door-hardware",
    familySlug: "glass-hardware",
    familyTitle: "Glass Hardware",
    slug: "pull-handle",
    title: "Pull Handle",
    description:
      "TG.PH pull handle products from the old TUR Glass Hardware catalogue.",
    shortDescription: "TG.PH pull handles for Glass Hardware applications.",
    image: "/tur/door-hardware/categories/default-769966786201111.jpg",
    imageAlt: "TG.PH pull handle — architectural glass door pull handle",
    eyebrow: "Glass Hardware - Pull Handles",
    keywords: ["TG.PH001", "TG.PH024", "pull handle", "Glass Hardware"],
  },
  {
    section: "door-hardware",
    familySlug: "glass-hardware",
    familyTitle: "Glass Hardware",
    slug: "lipseal",
    title: "Lipseal",
    description:
      "TG.LS lipseal products from the old TUR Glass Hardware catalogue.",
    shortDescription: "TG.LS lipseal products for glass edge sealing.",
    image: "/tur/door-hardware/categories/default-1292103519201111.jpg",
    imageAlt: "TG.LS lipseal — glass edge sealing for frameless glass doors",
    eyebrow: "Glass Hardware - Lipseal",
    keywords: ["TG.LS101", "TG.LS108", "lipseal", "glass lip seal"],
  },

  // ── Access Control ─────────────────────────────────────────────────────────
  {
    section: "door-hardware",
    familySlug: "access-control",
    familyTitle: "Access Control",
    slug: "electromagnetic-locks",
    title: "Electromagnetic Locks",
    description:
      "Electromagnetic locks for access-controlled single and double door applications, including TU single and double magnet lock ranges.",
    shortDescription:
      "TU electromagnetic locks for secure access-controlled openings.",
    image: "/tur/door-hardware/categories/default-228066963201112.jpg",
    imageAlt: "TU electromagnetic locks — surface-mounted access control maglocks",
    eyebrow: "Access Control · Electromagnetic Locks",
    keywords: [
      "electromagnetic lock",
      "maglock",
      "TU.300",
      "TU.600",
      "TU.800",
      "TU.1200",
      "TU.D600",
      "TU.D800",
      "TU.D1200",
      "access control locking",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "access-control",
    familyTitle: "Access Control",
    slug: "electric-strikes",
    title: "Electric Strikes",
    description:
      "Electric strike solutions for access-controlled entry — surface-mounted and frame-integrated models compatible with standard locksets and access control systems.",
    shortDescription:
      "Electric strikes for integrated release and access-controlled door operation.",
    image: "/tur/door-hardware/categories/default-66092838201112.jpg",
    imageAlt: "TU electric strikes — ANSI rim strike and electric release hardware",
    eyebrow: "Access Control · Electric Strikes",
    keywords: [
      "electric strike",
      "TU.1296",
      "TU.1297",
      "surface mounted electric strike",
      "rim exit device strike",
      "access control strike",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "access-control",
    familyTitle: "Access Control",
    slug: "armature-mounting-accessories",
    title: "Armature Mounting Accessories",
    description:
      "Mounting brackets, Z-brackets and armature accessories for coordinated electromagnetic lock installation across single, double and glass door configurations.",
    shortDescription:
      "Z-brackets, L-brackets and mounting plates for electromagnetic lock installation.",
    image: "/tur/door-hardware/categories/default-42037815201112.jpg",
    imageAlt: "Armature mounting accessories — brackets for electromagnetic lock installation",
    eyebrow: "Access Control · Mounting Accessories",
    keywords: [
      "armature mounting bracket",
      "Z-bracket electromagnetic lock",
      "TU.600 bracket",
      "TU.810 bracket",
      "maglock mounting accessories",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "access-control",
    familyTitle: "Access Control",
    slug: "electromechanical-locking-devices",
    title: "Electromechanical Locking Devices",
    description:
      "Electromechanical locking devices integrating mechanical bolt function with electronic access release for secure, coordinated entry management at controlled openings.",
    shortDescription:
      "Mechanical bolt with electronic release for discreet access-controlled locking.",
    image: "/tur/door-hardware/categories/default-973600067201112.jpg",
    imageAlt: "Electromechanical locking devices — TU.L800 and TU.PBH-350 push bar",
    eyebrow: "Access Control · Electromechanical Locking",
    keywords: [
      "electromechanical lock",
      "TU.L800",
      "TU.PBH-350",
      "electromechanical mortise lock",
      "delayed egress push bar",
      "access control locking device",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "access-control",
    familyTitle: "Access Control",
    slug: "e-access",
    title: "E-ACCESS",
    description:
      "Electronic access control systems — proximity readers, keypads and credential-management hardware for secure, managed entry across commercial and institutional projects.",
    shortDescription:
      "Proximity readers, keypads and credential systems for electronic access management.",
    image: "/tur/door-hardware/categories/default-1195187513201112.jpg",
    imageAlt: "E-ACCESS proximity readers and Bluetooth access systems — EasiProx and E1196",
    eyebrow: "Access Control · E-ACCESS Systems",
    keywords: [
      "E-ACCESS",
      "EasiProx",
      "proximity reader",
      "access control reader",
      "E1196",
      "credential access system",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "access-control",
    familyTitle: "Access Control",
    slug: "digital-keypad-system",
    title: "Digital Keypad System",
    description:
      "Digital keypad systems for PIN-based standalone or networked access control — suitable for secondary authentication, back-of-house access and low-infrastructure entry points.",
    shortDescription:
      "PIN-based digital keypad systems for standalone or integrated access control.",
    image: "/tur/door-hardware/categories/default-941202816201112.jpg",
    imageAlt: "TU.DG-750 digital keypad system — PIN-based access control",
    eyebrow: "Access Control · Digital Keypad",
    keywords: [
      "digital keypad",
      "PIN access control",
      "TU.DG-750",
      "standalone keypad",
      "access control keypad",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "access-control",
    familyTitle: "Access Control",
    slug: "infrared-wireless-exit-devices",
    title: "Infrared & Wireless Exit Devices",
    description:
      "Infrared and wireless request-to-exit devices for touchless egress triggering — compatible with electromagnetic locks and access-controlled doors in hygiene-sensitive and high-traffic environments.",
    shortDescription:
      "Touchless infrared and wireless RTE devices for access-controlled egress.",
    image: "/tur/door-hardware/categories/default-107836858201112.jpg",
    imageAlt: "TU.RTS infrared request-to-exit sensors — touchless egress devices",
    eyebrow: "Access Control · Exit Devices",
    keywords: [
      "infrared exit device",
      "wireless exit device",
      "request to exit",
      "RTE sensor",
      "TU.RTS-600",
      "TU.RTS-500",
      "touchless egress",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "access-control",
    familyTitle: "Access Control",
    slug: "electromagnetic-door-holders",
    title: "Electromagnetic Door Holders",
    description:
      "Electromagnetic door hold-open devices for fire-door coordination and smoke-control integration — releasing automatically on alarm activation for compliant circulation management.",
    shortDescription:
      "Electromagnetic door holders for fire-door hold-open with automatic alarm release.",
    image: "/tur/door-hardware/categories/default-1789777103201112.jpg",
    imageAlt: "TU.D900 electromagnetic door holders — fire door hold-open devices",
    eyebrow: "Access Control · Door Holders",
    keywords: [
      "electromagnetic door holder",
      "fire door hold open",
      "TU.D900F",
      "TU.D900W",
      "TU.D990",
      "door holder smoke control",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "access-control",
    familyTitle: "Access Control",
    slug: "access-control-accessories",
    title: "Access Control Accessories",
    description:
      "Supporting accessories completing access control packages — door loops, power supplies, control panels, exit buttons and wiring accessories for coordinated project-wide electronic access systems.",
    shortDescription:
      "Door loops, power supplies and accessories completing access control installations.",
    image: "/tur/door-hardware/categories/default-936568577201112.jpg",
    imageAlt: "Access control accessories — door loops, magnetic contacts and power supplies",
    eyebrow: "Access Control · Accessories",
    keywords: [
      "access control accessories",
      "door loop",
      "TU.DL-400",
      "TU.DL-417ST",
      "TU.2071",
      "TU.2031",
      "power supply access control",
    ],
  },

  // ── Sealing Systems ──────────────────────────────────────────────────────────
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "door-bottom-seals",
    title: "Door Bottom Seals",
    description:
      "Automatic and surface-applied door bottom seals for controlling air, dust and sound at the threshold — including concealed channel, surface-mounted and surface-applied automatic drop-seal profiles.",
    shortDescription:
      "Automatic and surface door bottom seals for threshold draught and sound control.",
    image: "/tur/door-hardware/categories/default-70562155201109.jpg",
    imageAlt: "Door bottom seal profile — architectural threshold sealing system",
    eyebrow: "Sealing Systems · Door Bottom Seals",
    keywords: [
      "door bottom seal",
      "automatic door bottom seal",
      "threshold seal",
      "TS8Si",
      "TS70",
      "TS5A",
      "TS17B",
      "TS99Si",
      "draught seal",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "threshold-plate-seals",
    title: "Threshold Plate Seals",
    description:
      "Threshold plate seals combining a durable floor-mounted aluminium profile with an integrated rubber or neoprene seal — coordinating with door bottom seals for a complete threshold closure.",
    shortDescription:
      "Aluminium threshold plate seals for coordinated floor-level threshold closure.",
    image: "/tur/door-hardware/categories/default-1123808333201109.jpg",
    imageAlt: "Threshold plate seals — aluminium floor-mounted sealing profiles",
    eyebrow: "Sealing Systems · Threshold Plate Seals",
    keywords: [
      "threshold plate seal",
      "threshold seal",
      "TS115",
      "TS117Si",
      "TS111Si",
      "aluminium threshold",
      "floor seal",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "threshold-plates",
    title: "Threshold Plates",
    description:
      "Aluminium threshold plates providing a durable, architecturally clean floor-level transition — protecting the threshold area and coordinating with door bottom seals for complete perimeter performance.",
    shortDescription:
      "Aluminium threshold plates for clean floor transitions and perimeter coordination.",
    image: "/tur/door-hardware/categories/default-654990898201109.jpg",
    imageAlt: "Threshold plates — aluminium floor transition and door sealing",
    eyebrow: "Sealing Systems · Threshold Plates",
    keywords: [
      "threshold plate",
      "aluminium threshold",
      "TS19",
      "TS18",
      "TS27",
      "TS28",
      "TS77",
      "floor transition",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "intumescent-seals",
    title: "Intumescent Seals",
    description:
      "Intumescent fire and smoke seals for fire-rated door assemblies — heat-activated profiles that expand on fire exposure to close the gap between door leaf and frame, maintaining the fire rating of the assembly.",
    shortDescription:
      "Heat-activated intumescent seals for fire-rated door gap closure and smoke control.",
    image: "/tur/door-hardware/categories/default-1956765799201109.jpg",
    imageAlt: "Intumescent seals — heat-activated fire-rated door gap sealing",
    eyebrow: "Sealing Systems · Intumescent Seals",
    keywords: [
      "intumescent seal",
      "fire seal",
      "smoke seal",
      "TS114",
      "fire-rated door seal",
      "heat-activated seal",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "door-frame-or-perimeter-seals",
    title: "Door Frame Or Perimeter Seals",
    description:
      "Frame and perimeter sealing profiles for the door head and jambs — surface-applied, rebated and concealed options that seal the gap between door leaf and frame for draught, acoustic and smoke control.",
    shortDescription:
      "Surface and concealed perimeter seals for door head and jamb gap control.",
    image: "/tur/door-hardware/categories/default-1021603673201109.jpg",
    imageAlt: "Door frame and perimeter seals — head and jamb gap sealing profiles",
    eyebrow: "Sealing Systems · Perimeter Seals",
    keywords: [
      "door frame seal",
      "perimeter seal",
      "TS120",
      "TS69",
      "TS73",
      "TS124",
      "TS56",
      "TS78Si",
      "jamb seal",
      "head seal",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "astragals",
    title: "Astragals",
    description:
      "Astragal sealing profiles for the meeting edge of double doors — surface-applied or rebated seals that close the gap between active and inactive leaves for draught, acoustic and smoke control.",
    shortDescription:
      "Meeting-edge astragal seals for double-door draught and smoke control.",
    image: "/tur/door-hardware/categories/default-782518864201109.jpg",
    imageAlt: "Astragal seals — meeting edge sealing for double-door sets",
    eyebrow: "Sealing Systems · Astragals",
    keywords: [
      "astragal",
      "meeting edge seal",
      "double door seal",
      "TS16Si",
      "draught seal",
      "smoke seal",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "magnetic-astragals",
    title: "Magnetic Astragals",
    description:
      "Magnetic astragal sealing profiles for double-door sets — using magnetic attraction to achieve positive contact at the meeting edge for improved draught, acoustic and smoke performance over standard astragals.",
    shortDescription:
      "Magnetic astragals for positive contact sealing at double-door meeting edges.",
    image: "/tur/door-hardware/categories/default-756307014201109.jpg",
    imageAlt: "Magnetic astragals — positive contact meeting edge sealing for double doors",
    eyebrow: "Sealing Systems · Magnetic Astragals",
    keywords: [
      "magnetic astragal",
      "magnetic meeting edge seal",
      "double door seal",
      "TS65",
      "acoustic seal",
      "positive contact seal",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "self-adhesive-seals",
    title: "Self Adhesive Seals",
    description:
      "Self-adhesive foam and rubber sealing strips for supplementary draught, dust and light acoustic gap sealing — quick-installation profiles for door and window perimeter applications.",
    shortDescription:
      "Self-adhesive foam and rubber strips for supplementary door perimeter sealing.",
    image: "/tur/door-hardware/categories/default-1868387964201109.jpg",
    imageAlt: "Self-adhesive seals — foam and rubber strips for door perimeter sealing",
    eyebrow: "Sealing Systems · Self Adhesive Seals",
    keywords: [
      "self adhesive seal",
      "foam seal",
      "rubber seal",
      "TS48B",
      "draught strip",
      "perimeter seal",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "brush-strip-seals",
    title: "Brush Strip Seals",
    description:
      "Brush strip sealing profiles for door bottoms, thresholds and perimeter applications — flexible nylon bristle bundles that accommodate floor irregularities and varying clearances for dependable draught and dust control.",
    shortDescription:
      "Flexible brush strip seals for door bottom, threshold and perimeter sealing.",
    image: "/tur/door-hardware/categories/default-464847982201109.jpg",
    imageAlt: "Brush strip seals — flexible nylon bristle sealing profiles for door bottoms",
    eyebrow: "Sealing Systems · Brush Strip Seals",
    keywords: [
      "brush strip seal",
      "brush seal",
      "TS2A",
      "TS2B",
      "TS41",
      "TS74",
      "nylon brush seal",
      "draught seal",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "complementary-products",
    title: "Complementary Products",
    description:
      "Supporting accessories and completion items for coordinated sealing system packages — smoke seals, compression seals and specialist closure accessories for architectural door sets.",
    shortDescription:
      "Smoke seals, compression seals and accessories completing sealing system packages.",
    image: "/tur/door-hardware/categories/default-342301605201109.jpg",
    imageAlt: "Complementary sealing products — smoke seals and completion accessories",
    eyebrow: "Sealing Systems · Complementary Products",
    keywords: [
      "smoke seal",
      "compression seal",
      "sealing accessories",
      "TS62",
      "TS62BW",
      "door seal accessories",
    ],
  },
  {
    section: "door-hardware",
    familySlug: "sealing-systems",
    familyTitle: "Sealing Systems",
    slug: "weather-stripping",
    title: "Weather Stripping",
    description:
      "Weather stripping profiles for external and internal door applications — surface-applied rubber and foam strips that coordinate with threshold plates and perimeter seals for complete weather and draught performance.",
    shortDescription:
      "Surface-applied weather strips for external door draught and weather control.",
    image: "/tur/door-hardware/categories/default-1772346152201109.jpg",
    imageAlt: "Weather stripping — surface-applied rubber and foam door weather seals",
    eyebrow: "Sealing Systems · Weather Stripping",
    keywords: [
      "weather stripping",
      "weather strip",
      "TS600",
      "external door seal",
      "draught strip",
      "weather seal",
    ],
  },
];

export function getRouteGroup(
  section: CatalogSectionSlug,
  familySlug: string,
  groupSlug: string,
): CatalogRouteGroup | undefined {
  return routeGroups.find(
    (g) => g.section === section && g.familySlug === familySlug && g.slug === groupSlug,
  );
}

export function getRouteGroupsByFamily(
  section: CatalogSectionSlug,
  familySlug: string,
): CatalogRouteGroup[] {
  return routeGroups.filter((g) => g.section === section && g.familySlug === familySlug);
}
